table _Measures
	lineageTag: ac9f8480-1949-4c36-b27f-1505075e4e2e

	measure 'Model Name' = IF(COUNTROWS(VALUES('Semantic Models'[Semantic Model]))>1 , "Multiple Models",MAX('Semantic Models'[Semantic Model]))
		lineageTag: f5329119-36ff-4fa2-b32f-5053dac8cbeb

	column zzzMeasures
		dataType: string
		isHidden
		lineageTag: b7788fb4-fbba-4247-b660-30320e6a2c24
		summarizeBy: none
		sourceColumn: zzzMeasures

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition _Measures = m
		mode: import
		source =
				//
				//Tables/Views used for Model Documentation
				//Initial Development: Dan Friedman, Rye Perez, Andy Maser
				//March 2024
				//This query creates a table for local measures, used for custom visual formatting
				//Typical implementation should not require very much modification of this query
				
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Measures = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Measures", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Measures", "zzzMeasures"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

