table 'Calculation Items'
	lineageTag: f36e5349-3787-4e71-a62a-4fa7cfd6250e

	column 'Calculation Item Name'
		dataType: string
		lineageTag: a1c88ba5-df58-43bb-adb1-4f8b845914e2
		summarizeBy: none
		sourceColumn: Calculation Item Name

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 89b3df0e-dfd2-4293-9dbe-85169b11856a
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Expression
		dataType: string
		lineageTag: d194a168-56b2-44f0-9cee-e726af92152c
		summarizeBy: none
		sourceColumn: Expression

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: string
		lineageTag: d0fce997-3b6b-4451-ae28-448361bd5660
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column CalculationGroupID
		dataType: string
		lineageTag: 50f7bfbb-ac91-40c1-b25e-fbba4a9f0408
		summarizeBy: none
		sourceColumn: CalculationGroupID

		annotation SummarizationSetBy = Automatic

	column FormatStringDefinitionID
		dataType: string
		lineageTag: 59130b6d-7d45-4d86-9b41-02bcad36997f
		summarizeBy: none
		sourceColumn: FormatStringDefinitionID

		annotation SummarizationSetBy = Automatic

	column 'Calculation Group Name'
		dataType: string
		lineageTag: 76fb1220-a52e-46d6-9cfe-0c7ed4bd1fc7
		summarizeBy: none
		sourceColumn: Calculation Group Name

		annotation SummarizationSetBy = Automatic

	column SemanticModel
		dataType: string
		lineageTag: aa57add2-787d-4922-a259-662050825e48
		summarizeBy: none
		sourceColumn: SemanticModel

		annotation SummarizationSetBy = Automatic

	partition 'Calculation Items' = m
		mode: import
		source = ```
				//
				//Tables/Views used for Model Documentation
				//Created by 3Cloud, LLC
				//Initial Development: Dan Friedman, Rye Perez, Andy Maser
				//March 2024
				//This query pulls in all the relevant data about Calculation Items found in the model, for auto-documentation
				//Typical implementation should not require very much modification of this query
				let
				    Source = #table(type table[SemanticModel=text], { {SemanticModel} }),
				     #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(Source, {{"SemanticModel", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "SemanticModel"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"SemanticModel", type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type",{{"SemanticModel", Text.Trim, type text}}),
				    #"Add Tables" = Table.AddColumn(#"Trimmed Text" , "sources" , each 
				    let
				        _t = AnalysisServices.Database( WorkspaceConnection, [SemanticModel], [Query="EVALUATE INFO.CalculationItems() "])
				    in 
				        _t
				    ),
				    #"Expanded sources" = Table.ExpandTableColumn(#"Add Tables", "sources", {"[ID]","[Name]","[CalculationGroupID]","[FormatStringDefinitionID]","[Description]","[Expression]"},
				 {"[ID]","[Name]","[CalculationGroupID]","[FormatStringDefinitionID]","[Description]","[Expression]"}),
				        #"Remove left brackets [" = fnReplaceValues(#"Expanded sources", "[", ""),
				        #"Remove right brackets ]" = fnReplaceValues(#"Remove left brackets [", "]", ""),
				    #"Renamed Columns" = Table.RenameColumns(#"Remove right brackets ]",{{"Name", "Calculation Item Name"}}),
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"CalculationGroupID"}, #"Calculation Groups", {"ID"}, "Calculation Groups", JoinKind.LeftOuter),
				    #"Expanded Calculation Groups" = Table.ExpandTableColumn(#"Merged Queries", "Calculation Groups", {"Table Name"}, {"Table Name"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded Calculation Groups",{{"Table Name", "Calculation Group Name"}})
				in
				    #"Renamed Columns1"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

