table Columns
	lineageTag: 1b2978f9-9bc8-4af0-ba56-809d7398973e

	column ID
		dataType: string
		lineageTag: fc562dd2-17ae-46f2-85a3-c09d7f371e3e
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column TableID
		dataType: string
		lineageTag: 03552b30-eda2-4a11-b7fa-a11350fa1eb3
		summarizeBy: none
		sourceColumn: TableID

		annotation SummarizationSetBy = Automatic

	column 'Raw Description'
		dataType: string
		lineageTag: 403d1504-1004-46bd-b754-85c86561ce62
		summarizeBy: none
		sourceColumn: Raw Description

		annotation SummarizationSetBy = Automatic

	column IsHidden
		dataType: string
		lineageTag: 3be5ca81-3299-4e9d-96e6-423849e9f3f1
		summarizeBy: none
		sourceColumn: IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Source Column'
		dataType: string
		lineageTag: b663156f-4513-4f66-9f48-e13287b45c36
		summarizeBy: none
		sourceColumn: Source Column

		annotation SummarizationSetBy = Automatic

	column Expression
		dataType: string
		lineageTag: 07e77236-4809-4715-a27b-3cf18f0ea9ab
		summarizeBy: none
		sourceColumn: Expression

		annotation SummarizationSetBy = Automatic

	column FormatString
		dataType: string
		lineageTag: 52f9dd06-c310-4167-b62a-d39c1889a18f
		summarizeBy: none
		sourceColumn: FormatString

		annotation SummarizationSetBy = Automatic

	column 'Column Type '
		dataType: string
		lineageTag: 0b7e612f-3887-41a8-81cf-0e0ac22a7556
		summarizeBy: none
		sourceColumn: "Column Type "

		annotation SummarizationSetBy = Automatic

	column 'Column Name'
		dataType: string
		lineageTag: da2a4d89-7653-4591-aa63-2913d6f6f3aa
		summarizeBy: none
		sourceColumn: Column Name

		annotation SummarizationSetBy = Automatic

	column Description = IF([Column Type ] = "Standard" && [Raw Description] = "",[Column Name],[Raw Description])
		lineageTag: 0a3e1470-5878-4e23-949c-3fed663b6600
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Table Name'
		dataType: string
		lineageTag: 782f062a-421f-47aa-9ff9-0db139c1f140
		summarizeBy: none
		sourceColumn: Table Name

		annotation SummarizationSetBy = Automatic

	column SemanticModel
		dataType: string
		lineageTag: 573e8e82-86ae-4119-81a4-30661777f2ca
		summarizeBy: none
		sourceColumn: SemanticModel

		annotation SummarizationSetBy = Automatic

	column CompoundKey
		dataType: string
		lineageTag: 82fe2e83-2ed8-4eed-9c55-2084f626f8cb
		summarizeBy: none
		sourceColumn: CompoundKey

		annotation SummarizationSetBy = Automatic

	partition Columns = m
		mode: import
		source = ```
				//
				//Tables/Views used for Model Documentation
				//Created by 3Cloud, LLC
				//Initial Development: Dan Friedman, Rye Perez, Andy Maser
				//March 2024
				//This query pulls in all the relevant data about Columns found in the model, for auto-documentation
				//Typical implementation should not require very much modification of this query
				
				let
				    Source = #table(type table[SemanticModel=text], { {SemanticModel} }),
				     #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(Source, {{"SemanticModel", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "SemanticModel"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"SemanticModel", type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type",{{"SemanticModel", Text.Trim, type text}}),
				    #"Add Tables" = Table.AddColumn(#"Trimmed Text" , "sources" , each 
				    let
				        _t = AnalysisServices.Database( WorkspaceConnection, [SemanticModel], [Query="EVALUATE INFO.Columns() "])
				    in 
				        _t
				    ),
				    #"Expanded sources" = Table.ExpandTableColumn(#"Add Tables", "sources", {"[ID]", "[FormatString]", "[ExplicitName]", "[IsHidden]", "[Description]","[TableID]","[Expression]","[SourceColumn]"},
				 {"[ID]", "[FormatString]", "[ExplicitName]", "[IsHidden]", "[Description]","[TableID]","[Expression]","[SourceColumn]"}),
				        #"Remove left brackets [" = fnReplaceValues(#"Expanded sources", "[", ""),
				        #"Remove right brackets ]" = fnReplaceValues(#"Remove left brackets [", "]", ""),
				    #"Renamed Columns" = Table.RenameColumns(#"Remove right brackets ]",{{"ExplicitName", "Column Name"},{"Description","Raw Description"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([Column Name] <> "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61")),
				    #"Added Column Type" = Table.AddColumn(#"Filtered Rows", "Column Type ", each if [Expression] = null then "Standard" else "Calculated"),
				    #"Added Custom1" = Table.AddColumn(#"Added Column Type", "CompoundKey", each [SemanticModel] & Text.From([TableID])),
				    #"Merged Queries" = Table.NestedJoin(#"Added Custom1", {"CompoundKey"}, Tables, {"CompoundKey"}, "Tables", JoinKind.LeftOuter),
				    #"Expanded Tables" = Table.ExpandTableColumn(#"Merged Queries", "Tables", {"Table Name"}, {"Table Name"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded Tables",{{"SourceColumn", "Source Column"}})
				in
				    #"Renamed Columns1"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

