table Columns
	lineageTag: 1b2978f9-9bc8-4af0-ba56-809d7398973e

	column ID
		dataType: int64
		formatString: 0
		lineageTag: fc562dd2-17ae-46f2-85a3-c09d7f371e3e
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column TableID
		dataType: int64
		formatString: 0
		lineageTag: 03552b30-eda2-4a11-b7fa-a11350fa1eb3
		summarizeBy: count
		sourceColumn: TableID

		annotation SummarizationSetBy = Automatic

	column ExplicitDataType
		dataType: int64
		formatString: 0
		lineageTag: 73100842-1ff5-48a6-81ea-0ef37d2a3998
		summarizeBy: sum
		sourceColumn: ExplicitDataType

		annotation SummarizationSetBy = Automatic

	column DataCategory
		dataType: string
		lineageTag: da01c541-69bb-43c2-aec0-6903256d8717
		summarizeBy: none
		sourceColumn: DataCategory

		annotation SummarizationSetBy = Automatic

	column 'Raw Description'
		dataType: string
		lineageTag: 403d1504-1004-46bd-b754-85c86561ce62
		summarizeBy: none
		sourceColumn: Raw Description

		annotation SummarizationSetBy = Automatic

	column IsHidden
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3be5ca81-3299-4e9d-96e6-423849e9f3f1
		summarizeBy: none
		sourceColumn: IsHidden

		annotation SummarizationSetBy = Automatic

	column SummarizeBy
		dataType: int64
		formatString: 0
		lineageTag: 706385ed-7977-4a61-8c7f-1eb9ad825661
		summarizeBy: sum
		sourceColumn: SummarizeBy

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: int64
		formatString: 0
		lineageTag: 1f56bf9d-3bf1-4cdb-9a46-8e7595e00470
		summarizeBy: sum
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column SourceColumn
		dataType: string
		lineageTag: b663156f-4513-4f66-9f48-e13287b45c36
		summarizeBy: none
		sourceColumn: SourceColumn

		annotation SummarizationSetBy = Automatic

	column Expression
		dataType: string
		lineageTag: 07e77236-4809-4715-a27b-3cf18f0ea9ab
		summarizeBy: none
		sourceColumn: Expression

		annotation SummarizationSetBy = Automatic

	column FormatString
		dataType: string
		lineageTag: 52f9dd06-c310-4167-b62a-d39c1889a18f
		summarizeBy: none
		sourceColumn: FormatString

		annotation SummarizationSetBy = Automatic

	column SortByColumnID
		dataType: int64
		formatString: 0
		lineageTag: c7120691-ae61-430c-87c1-36e2d35a95c3
		summarizeBy: count
		sourceColumn: SortByColumnID

		annotation SummarizationSetBy = Automatic

	column AttributeHierarchyID
		dataType: int64
		formatString: 0
		lineageTag: 43715c84-3a2e-403c-938c-1f44419a6bb7
		summarizeBy: count
		sourceColumn: AttributeHierarchyID

		annotation SummarizationSetBy = Automatic

	column ModifiedTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 1c8a308f-ca8d-4138-af95-346b129526a0
		summarizeBy: none
		sourceColumn: ModifiedTime

		annotation SummarizationSetBy = Automatic

	column StructureModifiedTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 0f950121-efce-46f9-8d0c-642ad1d0b15e
		summarizeBy: none
		sourceColumn: StructureModifiedTime

		annotation SummarizationSetBy = Automatic

	column RefreshedTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 99d48a1c-4bd9-4b1f-8167-f09ca00ba140
		summarizeBy: none
		sourceColumn: RefreshedTime

		annotation SummarizationSetBy = Automatic

	column DisplayFolder
		dataType: string
		lineageTag: 3b33807e-d046-4fa3-b568-cd6573e68df4
		summarizeBy: none
		sourceColumn: DisplayFolder

		annotation SummarizationSetBy = Automatic

	column LineageTag
		dataType: string
		lineageTag: 47039fe9-fd1c-4878-ad4c-96ad8416f99f
		summarizeBy: none
		sourceColumn: LineageTag

		annotation SummarizationSetBy = Automatic

	column 'Column Type '
		dataType: string
		lineageTag: 0b7e612f-3887-41a8-81cf-0e0ac22a7556
		summarizeBy: none
		sourceColumn: "Column Type "

		annotation SummarizationSetBy = Automatic

	column 'Column Name'
		dataType: string
		lineageTag: da2a4d89-7653-4591-aa63-2913d6f6f3aa
		summarizeBy: none
		sourceColumn: Column Name

		annotation SummarizationSetBy = Automatic

	column Description = IF([Column Type ] = "Standard" && [Raw Description] = "",[Column Name],[Raw Description])
		dataType: string
		lineageTag: 0a3e1470-5878-4e23-949c-3fed663b6600
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Table Name'
		dataType: string
		lineageTag: 782f062a-421f-47aa-9ff9-0db139c1f140
		summarizeBy: none
		sourceColumn: Table Name

		annotation SummarizationSetBy = Automatic

	partition Columns = m
		mode: import
		source = ```
				//
				//Tables/Views used for Model Documentation
				//Initial Development: Dan Friedman, Rye Perez, Andy Maser
				//March 2024
				//This query pulls in all the relevant data about Columns found in the model, for auto-documentation
				//Typical implementation should not require very much modification of this query
				
				let
				    Source = AnalysisServices.Database(WorkspaceConnection, SemanticModel, 
				    [Query="
				      EVALUATE
				  INFO.Columns()
				  "]),
				        #"Remove left brackets [" = fnReplaceValues(Source, "[", ""),
				        #"Remove right brackets ]" = fnReplaceValues(#"Remove left brackets [", "]", ""),
				    #"Removed Columns" = Table.RemoveColumns(#"Remove right brackets ]",{ "InferredName", "InferredDataType", "State", "IsUnique", "IsKey", "IsNullable", "Alignment", "TableDetailPosition", "IsDefaultLabel", "IsDefaultImage", "ColumnStorageID", "ColumnOriginID", "IsAvailableInMDX", "SystemFlags", "KeepUniqueRows", "DisplayOrdinal", "ErrorMessage", "SourceProviderType", "EncodingHint", "RelatedColumnDetailsID", "AlternateOfID", "SourceLineageTag"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"ExplicitName", "Column Name"},{"Description","Raw Description"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([Column Name] <> "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61")),
				    #"Added Column Type" = Table.AddColumn(#"Filtered Rows", "Column Type ", each if [Expression] = null then "Standard" else "Calculated"),
				    #"Merged Queries" = Table.NestedJoin(#"Added Column Type", {"TableID"}, Tables, {"ID"}, "Tables", JoinKind.LeftOuter),
				    #"Expanded Tables" = Table.ExpandTableColumn(#"Merged Queries", "Tables", {"Table Name"}, {"Table Name"})
				in
				    #"Expanded Tables"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

