table Hierarchies
	lineageTag: dc173271-df88-4ce2-a0a2-2348b13368c7

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 5e891628-73d6-493b-af9f-7508b03a9106
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column TableID
		dataType: int64
		formatString: 0
		lineageTag: b19e3b09-6730-4956-a55a-8f6fb7560bf0
		summarizeBy: count
		sourceColumn: TableID

		annotation SummarizationSetBy = Automatic

	column 'Hierarchy Name'
		dataType: string
		lineageTag: 0d9cc110-c8b3-4107-8fa1-1250571b929b
		summarizeBy: none
		sourceColumn: Hierarchy Name

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: a1e7c663-8ac8-4c57-8934-ce3649a27f08
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column IsHidden
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 79468d30-15f5-4f5d-9c2e-f4ae76fb14bf
		summarizeBy: none
		sourceColumn: IsHidden

		annotation SummarizationSetBy = Automatic

	column State
		dataType: int64
		formatString: 0
		lineageTag: d2fac362-32a5-4f05-81d4-aca5021dd44a
		summarizeBy: sum
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column HierarchyStorageID
		dataType: int64
		formatString: 0
		lineageTag: ce69ddd4-0f94-4b30-b402-b8b9d357ca2c
		summarizeBy: count
		sourceColumn: HierarchyStorageID

		annotation SummarizationSetBy = Automatic

	column ModifiedTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 993d81d2-f7b0-4740-ab44-7b64fd0f5e20
		summarizeBy: none
		sourceColumn: ModifiedTime

		annotation SummarizationSetBy = Automatic

	column StructureModifiedTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 67fae8e0-ade9-4dab-86cc-c1e8b7a9e5b2
		summarizeBy: none
		sourceColumn: StructureModifiedTime

		annotation SummarizationSetBy = Automatic

	column RefreshedTime
		dataType: dateTime
		formatString: General Date
		lineageTag: b774710e-5830-444b-8f54-f7f3aa371e3b
		summarizeBy: none
		sourceColumn: RefreshedTime

		annotation SummarizationSetBy = Automatic

	column DisplayFolder
		dataType: string
		lineageTag: fc2ff0e0-9b33-4090-a44f-63a8795f8b0c
		summarizeBy: none
		sourceColumn: DisplayFolder

		annotation SummarizationSetBy = Automatic

	column HideMembers
		dataType: int64
		formatString: 0
		lineageTag: 54207e2d-0c3b-4f7b-b610-67e72eb0fc06
		summarizeBy: sum
		sourceColumn: HideMembers

		annotation SummarizationSetBy = Automatic

	column LineageTag
		dataType: string
		lineageTag: aebf7e99-6b48-42e2-a3b9-5800f2ea97ba
		summarizeBy: none
		sourceColumn: LineageTag

		annotation SummarizationSetBy = Automatic

	column SourceLineageTag
		dataType: string
		lineageTag: bbf35524-75fb-4913-a2ef-0f63d546aeb5
		summarizeBy: none
		sourceColumn: SourceLineageTag

		annotation SummarizationSetBy = Automatic

	column 'Table Name'
		dataType: string
		lineageTag: e64d619d-c4ac-4da9-88c6-9f70046b550c
		summarizeBy: none
		sourceColumn: Table Name

		annotation SummarizationSetBy = Automatic

	partition Hierarchies = m
		mode: import
		source = ```
				//
				//Tables/Views used for Model Documentation
				//Initial Development: Dan Friedman, Rye Perez, Andy Maser
				//March 2024
				//This query pulls in all the relevant data about Hierarchies found in the model, for auto-documentation
				//Typical implementation should not require very much modification of this query
				
				let
				    Source = AnalysisServices.Database(WorkspaceConnection, SemanticModel, 
				    [Query="
				      EVALUATE
				  INFO.HIERARCHIES()
				  "]),
				        #"Remove left brackets [" = fnReplaceValues(Source, "[", ""),
				        #"Remove right brackets ]" = fnReplaceValues(#"Remove left brackets [", "]", ""),
				    #"Merged Queries" = Table.NestedJoin(#"Remove right brackets ]", {"TableID"}, Tables, {"ID"}, "Tables", JoinKind.LeftOuter),
				    #"Expanded Tables" = Table.ExpandTableColumn(#"Merged Queries", "Tables", {"Table Name"}, {"Table Name"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Tables",{{"Name", "Hierarchy Name"}})
				in
				    #"Renamed Columns"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

