table 'Measure List'
	lineageTag: 8bb194de-ce1a-428c-8c04-f25e8835f99d

	column ID
		dataType: string
		lineageTag: 6719619a-e3a0-4900-a5ba-bf777fc8ecd1
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Measure Name'
		dataType: string
		lineageTag: d98fc3af-b5ef-43ef-8e77-e3a7b5c85fde
		summarizeBy: none
		sourceColumn: Measure Name

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 1c3400ec-d61a-49da-9c12-79ff21f74fbf
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Expression
		dataType: string
		lineageTag: 0879b70a-a7b3-4deb-a2f0-e317cc2e051d
		summarizeBy: none
		sourceColumn: Expression

		annotation SummarizationSetBy = Automatic

	column FormatString
		dataType: string
		lineageTag: 854532c5-cd58-4376-941f-3cc55fb9ef15
		summarizeBy: none
		sourceColumn: FormatString

		annotation SummarizationSetBy = Automatic

	column IsHidden
		dataType: string
		lineageTag: 15149706-d8fa-4edb-89e6-e91efb5ad7b4
		summarizeBy: none
		sourceColumn: IsHidden

		annotation SummarizationSetBy = Automatic

	column ModifiedTime
		dataType: string
		lineageTag: a77d5f2e-f594-47a4-a4ba-d17e8a25bddb
		summarizeBy: none
		sourceColumn: ModifiedTime

		annotation SummarizationSetBy = Automatic

	column DisplayFolder
		dataType: string
		lineageTag: 0170c506-d40d-49ad-9763-5ea91b970f43
		summarizeBy: none
		sourceColumn: DisplayFolder

		annotation SummarizationSetBy = Automatic

	column SemanticModel
		dataType: string
		lineageTag: 43adec6f-70ad-4d46-9fe1-dafa797cb82b
		summarizeBy: none
		sourceColumn: SemanticModel

		annotation SummarizationSetBy = Automatic

	column ModelID
		dataType: string
		lineageTag: 926249e2-afe6-4385-8100-c8d38d8b1a42
		summarizeBy: none
		sourceColumn: ModelID

		annotation SummarizationSetBy = Automatic

	partition 'Measure List' = m
		mode: import
		source = ```
				//
				//Tables/Views used for Model Documentation
				//Created by 3Cloud, LLC
				//Initial Development: Dan Friedman, Rye Perez, Andy Maser
				//March 2024
				//This query pulls in all the relevant data about measures found in the model, for auto-documentation
				//Typical implementation should not require very much modification of this query
				
				let
				    Source = #table(type table[SemanticModel=text], { {SemanticModel} }),
				     #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(Source, {{"SemanticModel", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "SemanticModel"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"SemanticModel", type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type",{{"SemanticModel", Text.Trim, type text}}),
				    #"Add Tables" = Table.AddColumn(#"Trimmed Text" , "sources" , each 
				    let
				        _t = AnalysisServices.Database( WorkspaceConnection, [SemanticModel], [Query="EVALUATE INFO.MEASURES() "])
				    in 
				        _t
				    ),
				    #"Expanded sources" = Table.ExpandTableColumn(#"Add Tables", "sources", {"[ID]", "[ModelID]", "[Name]", "[Expression]", "[Description]", "[IsHidden]", "[FormatString]", "[ModifiedTime]",  "[DisplayFolder]"},
				
				 {"[ID]", "[ModelID]", "[Name]", "[Expression]", "[Description]", "[IsHidden]", "[FormatString]", "[ModifiedTime]",  "[DisplayFolder]"}),
				        #"Remove left brackets [" = fnReplaceValues(#"Expanded sources", "[", ""),
				        #"Remove right brackets ]" = fnReplaceValues(#"Remove left brackets [", "]", ""),
				    #"Renamed Columns" = Table.RenameColumns(#"Remove right brackets ]",{{"Name", "Measure Name"}})
				in
				    #"Renamed Columns"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

