table Partitions
	isHidden
	lineageTag: d632cf20-c5ac-428b-86c9-ca7ba0a45660

	column ID
		dataType: string
		isHidden
		lineageTag: 83b56511-c4db-4d49-94f2-09b4718c3e76
		summarizeBy: none
		sourceColumn: ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TableID
		dataType: string
		isHidden
		lineageTag: f1776b22-26db-4f8c-aa0d-202594ef3ad1
		summarizeBy: none
		sourceColumn: TableID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Partition Name'
		dataType: string
		isHidden
		lineageTag: e8f67b09-d8c9-4cbc-ad91-2463706a1264
		summarizeBy: none
		sourceColumn: Partition Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		isHidden
		lineageTag: ed635106-8fb8-45a0-9c3a-b469f58a4888
		summarizeBy: none
		sourceColumn: Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ModifiedTime
		dataType: string
		isHidden
		lineageTag: c3c63d53-7173-421b-be41-4ec58fa48b4b
		summarizeBy: none
		sourceColumn: ModifiedTime

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RefreshedTime
		dataType: string
		isHidden
		lineageTag: 60ede14a-b385-40eb-9450-325bec8145c4
		summarizeBy: none
		sourceColumn: RefreshedTime

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RangeStart
		dataType: string
		isHidden
		lineageTag: 0685c3f3-ee7e-40e2-92ba-abc3bf7c8f5f
		summarizeBy: none
		sourceColumn: RangeStart

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RangeEnd
		dataType: string
		isHidden
		lineageTag: 81ba5429-74a0-4c88-86ef-8fc7ac3bbdb9
		summarizeBy: none
		sourceColumn: RangeEnd

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Table Name'
		dataType: string
		isHidden
		lineageTag: bcd0aba2-1f7f-45f8-be7b-3b7622d31985
		summarizeBy: none
		sourceColumn: Table Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SemanticModel
		dataType: string
		lineageTag: d73d943c-8b6c-437d-9093-0dd02b45395f
		summarizeBy: none
		sourceColumn: SemanticModel

		annotation SummarizationSetBy = Automatic

	column QueryDefinition
		dataType: string
		lineageTag: 50a1edb5-df96-4eab-8d27-e8565019a9e3
		summarizeBy: none
		sourceColumn: QueryDefinition

		annotation SummarizationSetBy = Automatic

	column CompoundKey
		dataType: string
		lineageTag: fea4f369-f85c-4ac3-9d44-f22437e7426e
		summarizeBy: none
		sourceColumn: CompoundKey

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: 71b3f67d-cf38-423d-9ad9-639782da7012
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	partition Partitions = m
		mode: import
		source = ```
				//
				//Tables/Views used for Model Documentation
				//Created by 3Cloud, LLC
				//Initial Development: Dan Friedman, Rye Perez, Andy Maser
				//March 2024
				//This query pulls in all the relevant data about Partitions found in the model, for auto-documentation.
				// This query is only used to collect the M query for each patrition
				
				let
				    Source = #table(type table[SemanticModel=text], { {SemanticModel} }),
				     #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(Source, {{"SemanticModel", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "SemanticModel"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"SemanticModel", type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type",{{"SemanticModel", Text.Trim, type text}}),
				    #"Add Tables" = Table.AddColumn(#"Trimmed Text" , "sources" , each 
				    let
				        _t = AnalysisServices.Database( WorkspaceConnection, [SemanticModel], [Query="EVALUATE INFO.Partitions() "])
				    in 
				        _t
				    ),
				    #"Expanded sources" = Table.ExpandTableColumn(#"Add Tables", "sources", {"[ID]","[Source]", "[TableID]", "[Name]", "[QueryDefinition]", "[Description]", "[RefreshedTime]", "[RangeStart]", "[ModifiedTime]", "[RangeEnd]"},
				                                                                                {"[ID]","[Source]", "[TableID]", "[Name]", "[QueryDefinition]", "[Description]", "[RefreshedTime]", "[RangeStart]", "[ModifiedTime]", "[RangeEnd]"}),
				        #"Remove left brackets [" = fnReplaceValues(#"Expanded sources", "[", ""),
				        #"Remove right brackets ]" = fnReplaceValues(#"Remove left brackets [", "]", ""),
				    #"Renamed Columns" = Table.RenameColumns(#"Remove right brackets ]",{{"Name", "Partition Name"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "CompoundKey", each [SemanticModel] & Text.From([TableID])),
				    #"Merged Queries" = Table.NestedJoin(#"Added Custom", {"CompoundKey"}, Tables, {"CompoundKey"}, "Tables", JoinKind.LeftOuter),
				    #"Expanded Tables" = Table.ExpandTableColumn(#"Merged Queries", "Tables", {"Table Name"}, {"Table Name"})
				in
				    #"Expanded Tables"
				```

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

